### PR TITLE
Forward propertynames to bounds

### LINKED ISSUE #25: Forward `propertynames` to bounds
I am not sure whether this is intentional, because we only want to have access to the dimensions separately but accessing the bounds key of an extent is throwing an error. 
This is especially confusing because it tab completes only to ext.bounds and not the separate dimensions to then error. 

```julia
julia> ext = Extent(X=(1,2),Y=(0,4))
Extent(X = (1, 2), Y = (0, 4))

julia> ext.bounds
ERROR: Extent has no field bounds
Stacktrace:
 [1] getproperty(ext::Extent{(:X, :Y), Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}}}, key::Symbol)
   @ Extents ~/.julia/packages/Extents/LzSHL/src/Extents.jl:53
 [2] top-level scope
   @ REPL[45]:1
```

### PR DESCRIPTION
**Pull request by felixcremer**
This closes #25

### CODE REVIEW

File: src/Extents.jl [hunk 1]
```diff
@@ -53,6 +53,7 @@ function Base.getproperty(ext::Extent, key::Symbol)
     haskey(bounds(ext), key) || throw(ErrorException("Extent has no field $key"))
     getproperty(bounds(ext), key)
 end
+Base.propertynames(ext::Extent) =propertynames(getfield(ext, :bounds))
```
Comment (rafaqz) [inline src/Extents.jl:56]:
```suggestion
Base.propertynames(ext::Extent) = propertynames(getfield(ext, :bounds))
```

File: test/runtests.jl [hunk 2]
```diff
@@ -17,6 +17,7 @@ end
 
 @testset "getproperty" begin
     @test ex3.X == (1, 2)
+    @test propertynames(ex3) == (:X,:Y, :Z)
```
Comment (rafaqz) [inline test/runtests.jl:20]:
```suggestion
    @test propertynames(ex3) == (:X, :Y, :Z)
```
